### ISSUE TITLE
Password Regex is Wrong

### ISSUE THREAD

**Issue by fvthree** [basarbk/tdd-spring-react#1]
I tried ur regex on regex101 site and it's not working.  Then i found this site which has the working regex exp. 

http://html5pattern.com/Passwords

**Comment by basarbk** [comment]
The regex in code is `^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).*$` . [User.java](https://github.com/basarbk/tdd-spring-react/blob/580115227ab57c78806a42a59574bd665b14af11/hoaxify-backend/src/main/java/com/hoaxify/hoaxify/user/User.java#L47)
There is an extra backslash before `\d` (digit match of regex). If you remove it and try it in regex101, you can confirm this regex is correct.
[https://regex101.com/r/8EGOzF/2](https://regex101.com/r/8EGOzF/2)

In Java, backslash is an escape character. So that's why the format of the regex is a little bit different than what you see on regex101.
You can check following articles about regex in java
[https://www.vogella.com/tutorials/JavaRegularExpressions/article.html#backslashes-in-java](https://www.vogella.com/tutorials/JavaRegularExpressions/article.html#backslashes-in-java)
[https://www.regular-expressions.info/java.html](https://www.regular-expressions.info/java.html)
